In [1]:
import numpy as np

In [2]:
np.__version__

'1.20.1'

In [3]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularl

#### Numpy with List

In [4]:
### list stores heterogenoues data

l = [1,2,3,4,5]

In [5]:
type(l)

list

In [6]:
np.array(l)

array([1, 2, 3, 4, 5])

In [7]:
type(np.array(l))  ### numpy converts in to homogeneous

numpy.ndarray

In [9]:
l1 = [1,2,3,4,5, "sandeep"]
arr1 = np.array(l1)
arr1

### u11 means unicode string

array(['1', '2', '3', '4', '5', 'sandeep'], dtype='<U11')

#### 1D Array

In [10]:
arr1=np.array([1,2,3])
arr1.ndim

1

In [12]:
arr2=np.array([[1,2,3], [4,5,6]])
arr2.ndim

2

#### Matrix

In [13]:
l3 = [8,4,3,2]
np.matrix(l3)

matrix([[8, 4, 3, 2]])

#### Types of np.array

In [14]:
np.array([[[1,2], [4,5], [9,8]]])

array([[[1, 2],
        [4, 5],
        [9, 8]]])

In [15]:
np.asarray([[[1,2], [4,5], [9,8]]])

array([[[1, 2],
        [4, 5],
        [9, 8]]])

In [16]:
np.asanyarray([[[1,2], [4,5], [9,8]]])

array([[[1, 2],
        [4, 5],
        [9, 8]]])

#### Numpy with tupple

In [18]:
t = ([1,2,3], [9,8,7])
type(t)

tuple

In [19]:
np.array(t)

array([[1, 2, 3],
       [9, 8, 7]])

#### Numpy with Scaler

In [20]:
s= 5
np.array(s)

array(5)

#### Shallow copy and Deep copy

In [21]:
l4=[1,2,3,4,5]
arr4 = np.array(l4)
arr4

array([1, 2, 3, 4, 5])

In [24]:
a = arr4

In [25]:
a[0] = 1111

In [26]:
arr4

array([1111,    2,    3,    4,    5])

- change in "a" cause "arr" change  ----> Shallow copy

In [33]:
l5=[1,2,3,4,5]
arr5 = np.array(l5)
arr5

array([1, 2, 3, 4, 5])

In [34]:
b = arr5.copy()

In [31]:
b[0] = 2222

In [35]:
arr5

array([1, 2, 3, 4, 5])

#### Shape and size

In [41]:
list6 = ([[1,4,8], [8,4,2]])

In [42]:
arr6.shape

AttributeError: 'list' object has no attribute 'shape'

In [43]:
arr6 = np.array(list6)
arr6.shape

(2, 3)

In [44]:
arr6.size

6

In [66]:
arr6.dtype

dtype('int32')

#### Iterable

In [45]:
### in python

for i in range(5):
    print(i)

0
1
2
3
4


In [52]:
y = [i for i in range(5)]
print(y)

[0, 1, 2, 3, 4]


In [54]:
arr7 = np.array([i for i in range(5)])
print(arr7)
type(arr7)

[0 1 2 3 4]


numpy.ndarray

In [46]:
np.fromiter(range(5), int)

array([0, 1, 2, 3, 4])

In [55]:
np.fromiter(range(5), float)

array([0., 1., 2., 3., 4.])

#### From string separable

In [56]:
np.fromstring('22 33 44', sep=' ')

array([22., 33., 44.])

In [65]:
### normal python
s2 = '22 33 44'
print(s2.split())

# result = list(map(float, s.split()))
# print(result)


['22', '33', '44']


#### Float cannot be used in range

In [67]:
list(range(0,4))

[0, 1, 2, 3]

In [69]:
list(range(1.2,6.2))

TypeError: 'float' object cannot be interpreted as an integer

In [73]:
np.arange(1.2, 6.2, 0.2 ) #### start, end, gap

array([1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6,
       3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ])

In [75]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [76]:
np.logspace(1,5,10, base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [77]:
np.logspace(1,5,10, base=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

#### Zeros and Ones

In [78]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [79]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
#### 3d array without using bracket

np.zeros((3, 3, 4))  ## first 3 is dimension

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [81]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [82]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [83]:
np.ones((3,4)) + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])